version: '3.9'

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - media_files:/media
    command: >
      bash -c "uvicorn main:app --host=0.0.0.0 --reload"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  media_files:
  db-data: